{% set version = "0.31.0" %}

# sourced from:
# https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
{% set min_firefox = "91" %}

package:
  name: geckodriver
  version: {{ version }}

source:
  - url: https://github.com/mozilla/geckodriver/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 9648bfc1930eaeb648c438edc100eea3c03dc02b03fa90f4e439dd9dd20dcfbd
  - fn: geckodriver-{{ version }}-mpl-2.0.html
    url: https://www.mozilla.org/en-US/MPL/2.0/
    sha256: 1f5415d11845a92745d8ce1d8ef18725b56d0f58e8adafce14a1da95f3d4e0d3

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - sysroot_linux-64 2.17  # [linux64]

test:
  files:
    - test_selenium.py
  requires:
    - firefox >={{ min_firefox }}
    - pytest
    - python >=3.6
    - ruamel_yaml
    - selenium >=4
  commands:
    - geckodriver --version
    - geckodriver --help
    # this important just so we know that the version is accurate
    # https://github.com/mozilla/geckodriver/issues/1615
    - geckodriver --version | grep {{ version }}  # [not win]
    - conda inspect linkages -p $PREFIX geckodriver  # [not win]
    - conda inspect objects -p $PREFIX geckodriver  # [osx]
    # TODO: may be needed
    # - set -m && % xattr -r -d com.apple.quarantine $PREFIX/bin/geckodriver  # [osx]
    - pytest test_selenium.py

about:
  home: https://github.com/mozilla/geckodriver
  license: MPL-2.0
  license_file:
    - geckodriver-{{ version }}-mpl-2.0.html
    - THIRDPARTY.yml
  summary: |
    geckodriver is a proxy for using W3C WebDriver-compatible clients to
    interact with Gecko-based browsers.
  description: |
    This program provides the HTTP API described by the WebDriver protocol to
    communicate with Gecko browsers, such as Firefox. It translates calls into
    the Marionette remote protocol by acting as a proxy between the local- and
    remote ends.
  doc_url: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver
  dev_url: https://searchfox.org/mozilla-central/source/testing/geckodriver

extra:
  recipe-maintainers:
    - bollwyvl
