{% set name = "geckodriver" %}
{% set version = "0.25.0" %}
{% set changeset = "bdb64cf16b68c4a7212ba16aef425bce66d8f4ca" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-{{ changeset }}.tar.gz
  url: https://hg.mozilla.org/mozilla-central/archive/{{ changeset }}.tar.gz/testing/
  sha256: fa74a041e905f7007eb25f4a68d938b44142a1235dd8f0281ed62dc6adda1341

build:
  number: 0
  skip: true  # [win and vc!=14]
  msvc_compiler: 14.0  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - rust

test:
  commands:
    - which geckodriver  # [not win]
    - geckodriver --version
    - geckodriver --help
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: https://github.com/mozilla/geckodriver
  license: MPL-2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/mpl-2.0.txt'
  summary: |
    geckodriver is a proxy for using W3C WebDriver-compatible clients to
    interact with Gecko-based browsers.
  description: |
    This program provides the HTTP API described by the WebDriver protocol to
    communicate with Gecko browsers, such as Firefox. It translates calls into
    the Marionette remote protocol by acting as a proxy between the local- and
    remote ends.
  doc_url: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver
  dev_url: https://searchfox.org/mozilla-central/source/testing/geckodriver

extra:
  recipe-maintainers:
    - bollwyvl
