# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.37.0
  # sourced from: https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
  firefox_min: "115"
  grep: ${{ "grep -iE" if unix else "findstr" }}

package:
  name: geckodriver
  version: ${{ version }}

source:
  url: https://github.com/mozilla/geckodriver/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 713f2b3029b6b7af485450528164c6571df273d72de6009352c5c3c0c3211d8c

build:
  number: 0
  skip: win and vc<14
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: osx
        then:
          - export RUSTFLAGS="-C link-args=-Wl,-rpath,${PREFIX}/lib"
      - if: linux
        then:
          - export RUSTFLAGS="-C link-arg=-Wl,-rpath-link,${PREFIX}/lib -L${PREFIX}/lib"
      - cargo auditable install --no-track --bins --locked --profile=release --path=. --root "${{ PREFIX }}"
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml
      - if: win
        then:
          # Scripts used for historical reasons
          - move "%PREFIX%\bin\geckodriver.exe" "%PREFIX%\Scripts\geckodriver.exe"

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - files:
      recipe:
        - test_selenium.py
    requirements:
      run:
        - firefox >=${{ firefox_min }}
        - python >=${{ python_min }}
        - selenium
        - pytest
        - if: win
          then:
            - m2-grep
    script:
      env:
        MOZ_HEADLESS: "1"
      content:
        - geckodriver --version
        - geckodriver --help
        - geckodriver --version | ${{ grep }} "${{ version | replace('.', '\\.') }}"
        - pytest test_selenium.py

about:
  license: MPL-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  summary: |
    geckodriver is a proxy for using W3C WebDriver-compatible clients to
    interact with Gecko-based browsers.
  description: |
    This program provides the HTTP API described by the WebDriver protocol to
    communicate with Gecko browsers, such as Firefox. It translates calls into
    the Marionette remote protocol by acting as a proxy between the local- and
    remote ends.
  homepage: https://crates.io/crates/geckodriver
  repository: https://github.com/mozilla/geckodriver
  documentation: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver

extra:
  recipe-maintainers:
    - bollwyvl
