travis:
  secure:
    BINSTAR_TOKEN: E44076D/ZrAXBXs4EiyiNT8ueFnhK67J4ZHMVBbHn4QLmxBULHGaA0sTjGiU9DgqwrUdDpG6axXPQZoEnWc4pChzcH6/H72voZp7q8DsBXEMZgedn3bb/qakmaScOWoOc0bMOKCVCl0fEJxtuLIHaekx+4fMX0Bpt+3SkK5zA3YF1sTCzS9l9RERXRdQhvUxGYswLW+DZFbWsZuMixl9ZY2VRQ7+aKrBXnp2XraRC10joX/OQkr6tLjL0YFcz+62oRwfV+92ALZXNDmrpW7g9bfPXc+j1b2ea0Hgh6xTvUHxJUVcJ/pcaH1zcSuNi1mYieaEumqxL9gBGa2rrYKXTwmVjg8ZL1HJg4Ef28wu99NV46wDOvHxZaQlu8JvZUnJUkjAszKw2xPLYjr1ZRNV86rsmsejmr0Y2ryX5hoc0PNjqtUmGQS+talZg6VreE2A+Hz7wNBU9Ks+uE/HJmHhrWY+gdcnnvam7Mh3ZMGNooENpP5RO03JvdnppQDuFPgjDSNNw508/MBHOylt/yR6jrbbuYRBYMd+T7rwo8S/Jqn1gZ8fBsPqYeRwBUt0+jNbDcwkwTxy/kumjMpALCHvs4hi9QfRC7pybjX8U0WWgrLBwBnvV+8muynpsZcGdwnUppfS7xBH9qFE6Xo9Vut/EObJXn4zk3tws9UF/O8q1E8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
